/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

INSERT INTO [dbo].[User] ([Username],[Password],[FirstName],[LastName],[DateCreated],[Email],[ImageUrl])
VALUES ('admin','admin','Admin','Admin',GETDATE(),'admin@admin.com',null)
INSERT INTO [dbo].[User] ([Username],[Password],[FirstName],[LastName],[DateCreated],[Email],[ImageUrl])
VALUES ('igrac1','igrac1','Igrac1','Igrac1',GETDATE(),'igrac1@igrac1.com',null)
INSERT INTO [dbo].[User] ([Username],[Password],[FirstName],[LastName],[DateCreated],[Email],[ImageUrl])
VALUES ('igrac2','igrac2','Igrac2','Igrac2',GETDATE(),'igrac2@igrac2.com',null)

INSERT INTO [dbo].[Training] ([UserId])
VALUES (1)
INSERT INTO [dbo].[Training] ([UserId])
VALUES (2)
INSERT INTO [dbo].[Training] ([UserId])
VALUES (3)

/*word definition dummy*/
INSERT INTO [dbo].[WordDefinition] ([CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3],[Word])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu','Smisljam')
INSERT INTO [dbo].[WordDefinition] ([CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3],[Word])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu','Smisljam')
INSERT INTO [dbo].[WordDefinition] ([CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3],[Word])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu','Smisljam')
INSERT INTO [dbo].[WordDefinition] ([CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3],[Word])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu','Smisljam')
INSERT INTO [dbo].[WordDefinition] ([CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3],[Word])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu','Smisljam')
INSERT INTO [dbo].[WordDefinition] ([CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3],[Word])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu','Smisljam')
INSERT INTO [dbo].[WordDefinition] ([CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3],[Word])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu','Smisljam')
INSERT INTO [dbo].[WordDefinition] ([CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3],[Word])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu','Smisljam')
INSERT INTO [dbo].[WordDefinition] ([CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3],[Word])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu','Smisljam')
INSERT INTO [dbo].[WordDefinition] ([CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3],[Word])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu','Smisljam')
INSERT INTO [dbo].[WordDefinition] ([CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3],[Word])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu','Smisljam')
INSERT INTO [dbo].[WordDefinition] ([CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3],[Word])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu','Smisljam')
INSERT INTO [dbo].[WordDefinition] ([CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3],[Word])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu','Smisljam')
INSERT INTO [dbo].[WordDefinition] ([CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3],[Word])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu','Smisljam')
INSERT INTO [dbo].[WordDefinition] ([CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3],[Word])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu','Smisljam')
INSERT INTO [dbo].[WordDefinition] ([CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3],[Word])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu','Smisljam')
INSERT INTO [dbo].[WordDefinition] ([CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3],[Word])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu','Smisljam')
INSERT INTO [dbo].[WordDefinition] ([CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3],[Word])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu','Smisljam')
INSERT INTO [dbo].[WordDefinition] ([CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3],[Word])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu','Smisljam')
INSERT INTO [dbo].[WordDefinition] ([CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3],[Word])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu','Smisljam')
INSERT INTO [dbo].[WordDefinition] ([CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3],[Word])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu','Smisljam')
INSERT INTO [dbo].[WordDefinition] ([CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3],[Word])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu','Smisljam')
INSERT INTO [dbo].[WordDefinition] ([CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3],[Word])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu','Smisljam')
INSERT INTO [dbo].[WordDefinition] ([CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3],[Word])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu','Smisljam')
INSERT INTO [dbo].[WordDefinition] ([CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3],[Word])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu','Smisljam')

/*word synonyms dummy*/

INSERT INTO [dbo].[WordSynonyms] ([CorrectAnswer1],[CorrectAnswer2],[WrongAnswer1],[WrongAnswer2])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu')
INSERT INTO [dbo].[WordSynonyms] ([CorrectAnswer1],[CorrectAnswer2],[WrongAnswer1],[WrongAnswer2])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu')
INSERT INTO [dbo].[WordSynonyms] ([CorrectAnswer1],[CorrectAnswer2],[WrongAnswer1],[WrongAnswer2])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu')
INSERT INTO [dbo].[WordSynonyms] ([CorrectAnswer1],[CorrectAnswer2],[WrongAnswer1],[WrongAnswer2])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu')
INSERT INTO [dbo].[WordSynonyms] ([CorrectAnswer1],[CorrectAnswer2],[WrongAnswer1],[WrongAnswer2])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu')
INSERT INTO [dbo].[WordSynonyms] ([CorrectAnswer1],[CorrectAnswer2],[WrongAnswer1],[WrongAnswer2])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu')
INSERT INTO [dbo].[WordSynonyms] ([CorrectAnswer1],[CorrectAnswer2],[WrongAnswer1],[WrongAnswer2])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu')
INSERT INTO [dbo].[WordSynonyms] ([CorrectAnswer1],[CorrectAnswer2],[WrongAnswer1],[WrongAnswer2])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu')
INSERT INTO [dbo].[WordSynonyms] ([CorrectAnswer1],[CorrectAnswer2],[WrongAnswer1],[WrongAnswer2])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu')
INSERT INTO [dbo].[WordSynonyms] ([CorrectAnswer1],[CorrectAnswer2],[WrongAnswer1],[WrongAnswer2])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu')
INSERT INTO [dbo].[WordSynonyms] ([CorrectAnswer1],[CorrectAnswer2],[WrongAnswer1],[WrongAnswer2])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu')
INSERT INTO [dbo].[WordSynonyms] ([CorrectAnswer1],[CorrectAnswer2],[WrongAnswer1],[WrongAnswer2])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu')
INSERT INTO [dbo].[WordSynonyms] ([CorrectAnswer1],[CorrectAnswer2],[WrongAnswer1],[WrongAnswer2])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu')
INSERT INTO [dbo].[WordSynonyms] ([CorrectAnswer1],[CorrectAnswer2],[WrongAnswer1],[WrongAnswer2])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu')
INSERT INTO [dbo].[WordSynonyms] ([CorrectAnswer1],[CorrectAnswer2],[WrongAnswer1],[WrongAnswer2])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu')
INSERT INTO [dbo].[WordSynonyms] ([CorrectAnswer1],[CorrectAnswer2],[WrongAnswer1],[WrongAnswer2])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu')
INSERT INTO [dbo].[WordSynonyms] ([CorrectAnswer1],[CorrectAnswer2],[WrongAnswer1],[WrongAnswer2])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu')
INSERT INTO [dbo].[WordSynonyms] ([CorrectAnswer1],[CorrectAnswer2],[WrongAnswer1],[WrongAnswer2])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu')
INSERT INTO [dbo].[WordSynonyms] ([CorrectAnswer1],[CorrectAnswer2],[WrongAnswer1],[WrongAnswer2])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu')
INSERT INTO [dbo].[WordSynonyms] ([CorrectAnswer1],[CorrectAnswer2],[WrongAnswer1],[WrongAnswer2])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu')
INSERT INTO [dbo].[WordSynonyms] ([CorrectAnswer1],[CorrectAnswer2],[WrongAnswer1],[WrongAnswer2])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu')
INSERT INTO [dbo].[WordSynonyms] ([CorrectAnswer1],[CorrectAnswer2],[WrongAnswer1],[WrongAnswer2])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu')
INSERT INTO [dbo].[WordSynonyms] ([CorrectAnswer1],[CorrectAnswer2],[WrongAnswer1],[WrongAnswer2])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu')
INSERT INTO [dbo].[WordSynonyms] ([CorrectAnswer1],[CorrectAnswer2],[WrongAnswer1],[WrongAnswer2])
VALUES ('Neka Ga','Ovako','Sta cu','Ne mogu')

/*logic array dummy */

INSERT INTO [dbo].[LogicArray] ([Array],[CorrectNumber],[WrongNumber1],[WrongNumber2],[WrongNumber3])
VALUES ('1,_,3,4,5',2,1,3,4)
INSERT INTO [dbo].[LogicArray] ([Array],[CorrectNumber],[WrongNumber1],[WrongNumber2],[WrongNumber3])
VALUES ('1,_,3,4,5',2,1,3,4)
INSERT INTO [dbo].[LogicArray] ([Array],[CorrectNumber],[WrongNumber1],[WrongNumber2],[WrongNumber3])
VALUES ('1,_,3,4,5',2,1,3,4)
INSERT INTO [dbo].[LogicArray] ([Array],[CorrectNumber],[WrongNumber1],[WrongNumber2],[WrongNumber3])
VALUES ('1,_,3,4,5',2,1,3,4)
INSERT INTO [dbo].[LogicArray] ([Array],[CorrectNumber],[WrongNumber1],[WrongNumber2],[WrongNumber3])
VALUES ('1,_,3,4,5',2,1,3,4)
INSERT INTO [dbo].[LogicArray] ([Array],[CorrectNumber],[WrongNumber1],[WrongNumber2],[WrongNumber3])
VALUES ('1,_,3,4,5',2,1,3,4)
INSERT INTO [dbo].[LogicArray] ([Array],[CorrectNumber],[WrongNumber1],[WrongNumber2],[WrongNumber3])
VALUES ('1,_,3,4,5',2,1,3,4)
INSERT INTO [dbo].[LogicArray] ([Array],[CorrectNumber],[WrongNumber1],[WrongNumber2],[WrongNumber3])
VALUES ('1,_,3,4,5',2,1,3,4)
INSERT INTO [dbo].[LogicArray] ([Array],[CorrectNumber],[WrongNumber1],[WrongNumber2],[WrongNumber3])
VALUES ('1,_,3,4,5',2,1,3,4)
INSERT INTO [dbo].[LogicArray] ([Array],[CorrectNumber],[WrongNumber1],[WrongNumber2],[WrongNumber3])
VALUES ('1,_,3,4,5',2,1,3,4)
INSERT INTO [dbo].[LogicArray] ([Array],[CorrectNumber],[WrongNumber1],[WrongNumber2],[WrongNumber3])
VALUES ('1,_,3,4,5',2,1,3,4)
INSERT INTO [dbo].[LogicArray] ([Array],[CorrectNumber],[WrongNumber1],[WrongNumber2],[WrongNumber3])
VALUES ('1,_,3,4,5',2,1,3,4)
INSERT INTO [dbo].[LogicArray] ([Array],[CorrectNumber],[WrongNumber1],[WrongNumber2],[WrongNumber3])
VALUES ('1,_,3,4,5',2,1,3,4)
INSERT INTO [dbo].[LogicArray] ([Array],[CorrectNumber],[WrongNumber1],[WrongNumber2],[WrongNumber3])
VALUES ('1,_,3,4,5',2,1,3,4)
INSERT INTO [dbo].[LogicArray] ([Array],[CorrectNumber],[WrongNumber1],[WrongNumber2],[WrongNumber3])
VALUES ('1,_,3,4,5',2,1,3,4)
INSERT INTO [dbo].[LogicArray] ([Array],[CorrectNumber],[WrongNumber1],[WrongNumber2],[WrongNumber3])
VALUES ('1,_,3,4,5',2,1,3,4)
INSERT INTO [dbo].[LogicArray] ([Array],[CorrectNumber],[WrongNumber1],[WrongNumber2],[WrongNumber3])
VALUES ('1,_,3,4,5',2,1,3,4)
INSERT INTO [dbo].[LogicArray] ([Array],[CorrectNumber],[WrongNumber1],[WrongNumber2],[WrongNumber3])
VALUES ('1,_,3,4,5',2,1,3,4)
INSERT INTO [dbo].[LogicArray] ([Array],[CorrectNumber],[WrongNumber1],[WrongNumber2],[WrongNumber3])
VALUES ('1,_,3,4,5',2,1,3,4)
INSERT INTO [dbo].[LogicArray] ([Array],[CorrectNumber],[WrongNumber1],[WrongNumber2],[WrongNumber3])
VALUES ('1,_,3,4,5',2,1,3,4)
INSERT INTO [dbo].[LogicArray] ([Array],[CorrectNumber],[WrongNumber1],[WrongNumber2],[WrongNumber3])
VALUES ('1,_,3,4,5',2,1,3,4)
INSERT INTO [dbo].[LogicArray] ([Array],[CorrectNumber],[WrongNumber1],[WrongNumber2],[WrongNumber3])
VALUES ('1,_,3,4,5',2,1,3,4)
INSERT INTO [dbo].[LogicArray] ([Array],[CorrectNumber],[WrongNumber1],[WrongNumber2],[WrongNumber3])
VALUES ('1,_,3,4,5',2,1,3,4)
INSERT INTO [dbo].[LogicArray] ([Array],[CorrectNumber],[WrongNumber1],[WrongNumber2],[WrongNumber3])
VALUES ('1,_,3,4,5',2,1,3,4)

/*calculations dummy */

INSERT INTO [dbo].[Calculations] ([Expression],[CorrectResult],[WrongResult1],[WrongResult2],[WrongResult3])
VALUES ('2+2',4,5,6,1)
INSERT INTO [dbo].[Calculations] ([Expression],[CorrectResult],[WrongResult1],[WrongResult2],[WrongResult3])
VALUES ('2+2',4,5,6,1)
INSERT INTO [dbo].[Calculations] ([Expression],[CorrectResult],[WrongResult1],[WrongResult2],[WrongResult3])
VALUES ('2+2',4,5,6,1)
INSERT INTO [dbo].[Calculations] ([Expression],[CorrectResult],[WrongResult1],[WrongResult2],[WrongResult3])
VALUES ('2+2',4,5,6,1)
INSERT INTO [dbo].[Calculations] ([Expression],[CorrectResult],[WrongResult1],[WrongResult2],[WrongResult3])
VALUES ('2+2',4,5,6,1)
INSERT INTO [dbo].[Calculations] ([Expression],[CorrectResult],[WrongResult1],[WrongResult2],[WrongResult3])
VALUES ('2+2',4,5,6,1)
INSERT INTO [dbo].[Calculations] ([Expression],[CorrectResult],[WrongResult1],[WrongResult2],[WrongResult3])
VALUES ('2+2',4,5,6,1)
INSERT INTO [dbo].[Calculations] ([Expression],[CorrectResult],[WrongResult1],[WrongResult2],[WrongResult3])
VALUES ('2+2',4,5,6,1)
INSERT INTO [dbo].[Calculations] ([Expression],[CorrectResult],[WrongResult1],[WrongResult2],[WrongResult3])
VALUES ('2+2',4,5,6,1)
INSERT INTO [dbo].[Calculations] ([Expression],[CorrectResult],[WrongResult1],[WrongResult2],[WrongResult3])
VALUES ('2+2',4,5,6,1)
INSERT INTO [dbo].[Calculations] ([Expression],[CorrectResult],[WrongResult1],[WrongResult2],[WrongResult3])
VALUES ('2+2',4,5,6,1)
INSERT INTO [dbo].[Calculations] ([Expression],[CorrectResult],[WrongResult1],[WrongResult2],[WrongResult3])
VALUES ('2+2',4,5,6,1)
INSERT INTO [dbo].[Calculations] ([Expression],[CorrectResult],[WrongResult1],[WrongResult2],[WrongResult3])
VALUES ('2+2',4,5,6,1)
INSERT INTO [dbo].[Calculations] ([Expression],[CorrectResult],[WrongResult1],[WrongResult2],[WrongResult3])
VALUES ('2+2',4,5,6,1)
INSERT INTO [dbo].[Calculations] ([Expression],[CorrectResult],[WrongResult1],[WrongResult2],[WrongResult3])
VALUES ('2+2',4,5,6,1)
INSERT INTO [dbo].[Calculations] ([Expression],[CorrectResult],[WrongResult1],[WrongResult2],[WrongResult3])
VALUES ('2+2',4,5,6,1)
INSERT INTO [dbo].[Calculations] ([Expression],[CorrectResult],[WrongResult1],[WrongResult2],[WrongResult3])
VALUES ('2+2',4,5,6,1)
INSERT INTO [dbo].[Calculations] ([Expression],[CorrectResult],[WrongResult1],[WrongResult2],[WrongResult3])
VALUES ('2+2',4,5,6,1)
INSERT INTO [dbo].[Calculations] ([Expression],[CorrectResult],[WrongResult1],[WrongResult2],[WrongResult3])
VALUES ('2+2',4,5,6,1)
INSERT INTO [dbo].[Calculations] ([Expression],[CorrectResult],[WrongResult1],[WrongResult2],[WrongResult3])
VALUES ('2+2',4,5,6,1)
INSERT INTO [dbo].[Calculations] ([Expression],[CorrectResult],[WrongResult1],[WrongResult2],[WrongResult3])
VALUES ('2+2',4,5,6,1)
INSERT INTO [dbo].[Calculations] ([Expression],[CorrectResult],[WrongResult1],[WrongResult2],[WrongResult3])
VALUES ('2+2',4,5,6,1)
INSERT INTO [dbo].[Calculations] ([Expression],[CorrectResult],[WrongResult1],[WrongResult2],[WrongResult3])
VALUES ('2+2',4,5,6,1)
INSERT INTO [dbo].[Calculations] ([Expression],[CorrectResult],[WrongResult1],[WrongResult2],[WrongResult3])
VALUES ('2+2',4,5,6,1)
INSERT INTO [dbo].[Calculations] ([Expression],[CorrectResult],[WrongResult1],[WrongResult2],[WrongResult3])
VALUES ('2+2',4,5,6,1)
INSERT INTO [dbo].[Calculations] ([Expression],[CorrectResult],[WrongResult1],[WrongResult2],[WrongResult3])
VALUES ('2+2',4,5,6,1)
INSERT INTO [dbo].[Calculations] ([Expression],[CorrectResult],[WrongResult1],[WrongResult2],[WrongResult3])
VALUES ('2+2',4,5,6,1)
INSERT INTO [dbo].[Calculations] ([Expression],[CorrectResult],[WrongResult1],[WrongResult2],[WrongResult3])
VALUES ('2+2',4,5,6,1)

/* general knowledge dummy */

INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')
INSERT INTO [dbo].[GeneralKnowledge] ([Question],[CorrectAnswer],[WrongAnswer1],[WrongAnswer2],[WrongAnswer3])
VALUES ('KO je najveci car na svetu', 'Lesa','Pera','Mika','Zika')