//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Se7enQ.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calcuation
    {
        public int Id { get; set; }
        public string Expression { get; set; }
        public int CorrectResult { get; set; }
        public int WrongResult1 { get; set; }
        public int WrongResult2 { get; set; }
        public int WrongResult3 { get; set; }
    }
}
