//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Se7enQ.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GameQuestion()
        {
            this.Games = new HashSet<Game>();
        }
    
        public int Id { get; set; }
        public int WordSynonyms1 { get; set; }
        public int WordSynonyms2 { get; set; }
        public int WordSynonyms3 { get; set; }
        public int WordSynonyms4 { get; set; }
        public int WordDefinitions1 { get; set; }
        public int WordDefinitions2 { get; set; }
        public int WordDefinitions3 { get; set; }
        public Nullable<int> WordDefinitions4 { get; set; }
        public Nullable<int> LogicArray1 { get; set; }
        public int LogicArray2 { get; set; }
        public int LogicArray3 { get; set; }
        public int LogicArray4 { get; set; }
        public int Calculations1 { get; set; }
        public int Calculations2 { get; set; }
        public int Calculations3 { get; set; }
        public int Calculations4 { get; set; }
        public int GeneralKnowledge1 { get; set; }
        public int GeneralKnowledge2 { get; set; }
        public int GeneralKnowledge3 { get; set; }
        public int GeneralKnowledge4 { get; set; }
    
        public virtual Calculation Calculation { get; set; }
        public virtual Calculation Calculation1 { get; set; }
        public virtual Calculation Calculation2 { get; set; }
        public virtual Calculation Calculation3 { get; set; }
        public virtual WordDefinition WordDefinition { get; set; }
        public virtual WordDefinition WordDefinition1 { get; set; }
        public virtual WordDefinition WordDefinition2 { get; set; }
        public virtual WordDefinition WordDefinition3 { get; set; }
        public virtual GeneralKnowledge GeneralKnowledge { get; set; }
        public virtual GeneralKnowledge GeneralKnowledge5 { get; set; }
        public virtual GeneralKnowledge GeneralKnowledge6 { get; set; }
        public virtual GeneralKnowledge GeneralKnowledge7 { get; set; }
        public virtual LogicArray LogicArray { get; set; }
        public virtual LogicArray LogicArray5 { get; set; }
        public virtual LogicArray LogicArray6 { get; set; }
        public virtual LogicArray LogicArray7 { get; set; }
        public virtual WordSynonym WordSynonym { get; set; }
        public virtual WordSynonym WordSynonym1 { get; set; }
        public virtual WordSynonym WordSynonym2 { get; set; }
        public virtual WordSynonym WordSynonym3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game> Games { get; set; }
    }
}
