//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Se7enQ.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projection
    {
        public int Id { get; set; }
        public string C3DImage { get; set; }
        public string CorrectProjection { get; set; }
        public string WrongProjection1 { get; set; }
        public string WrongProjection2 { get; set; }
        public string WrongProjection3 { get; set; }
    }
}
