//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Se7enQ.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public int UserId { get; set; }
        public bool Calculations { get; set; }
        public bool GeneralKnowledge { get; set; }
        public bool LogicArray { get; set; }
        public bool Memory { get; set; }
        public bool Projections { get; set; }
        public bool WordDefinition { get; set; }
        public bool WordSynonyms { get; set; }
    
        public virtual User User { get; set; }
    }
}
